from modules.SharedVariables import SharedVariables
from modules.utility import *

from modules.commands.comment import comment
from modules.commands.create_board import create_board
from modules.commands.create_post import create_post
from modules.commands.delete_post import delete_post
from modules.commands.exit import client_exit
from modules.commands.help import command_list
from modules.commands.list_board import list_board
from modules.commands.list_post import list_post
from modules.commands.list_user import list_user
from modules.commands.login import login
from modules.commands.logout import logout
from modules.commands.read import read
from modules.commands.register import register
from modules.commands.update_post import update_post
from modules.commands.whoami import whoami
from modules.commands.create_chatroom import create_chatroom
from modules.commands.list_chatroom import list_chatroom
from modules.commands.join_chatroom import join_chatroom
from modules.commands.close_chatroom import close_chatroom
from modules.commands.restart_chatroom import restart_chatroom
